import { FormEvent, useCallback, useEffect, useState } from "react";
import { Activity, CheckCircle2, Gauge, LoaderCircle, Plus, RefreshCw, Settings, ShieldCheck, Trash2, Users } from "lucide-react";
import { supabase } from "../lib/supabase";

type Tab="users"|"boilers"|"limits"|"checklist"|"audit";
type Profile={id:string;full_name:string;email:string;role:"admin"|"supervisor"|"operator"|"technician";is_active:boolean;approval_status:"pending"|"approved"|"rejected";created_at:string};
type Boiler={id:number;code:string;name:string;boiler_type:string;capacity_tons:number;operational_status:"running"|"off"};
type Limit={id:number;reading_key:string;label:string;minimum:number;maximum:number;unit:string};
type Checklist={id:number;item_text:string;is_completed:boolean;sort_order:number};
type Audit={id:number;action:string;entity_type:string|null;entity_id:string|null;new_values:unknown;created_at:string};

export function AdminPanel({notify}:{notify:(text:string)=>void}){
 const[tab,setTab]=useState<Tab>("users"),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[profiles,setProfiles]=useState<Profile[]>([]),[boilers,setBoilers]=useState<Boiler[]>([]),[limits,setLimits]=useState<Limit[]>([]),[items,setItems]=useState<Checklist[]>([]),[audits,setAudits]=useState<Audit[]>([]);
 const[boilerForm,setBoilerForm]=useState({code:"",name:"",boiler_type:"Fire-tube",capacity_tons:"1"}),[itemText,setItemText]=useState("");
 const load=useCallback(async()=>{setLoading(true);const[p,b,l,c,a]=await Promise.all([supabase.from("profiles").select("id,full_name,email,role,is_active,approval_status,created_at").order("created_at",{ascending:false}),supabase.from("boilers").select("id,code,name,boiler_type,capacity_tons,operational_status").order("code"),supabase.from("operational_limits").select("id,reading_key,label,minimum,maximum,unit").order("id"),supabase.from("safety_checklist_items").select("id,item_text,is_completed,sort_order").order("sort_order"),supabase.from("audit_logs").select("id,action,entity_type,entity_id,new_values,created_at").order("created_at",{ascending:false}).limit(100)]);const first=[p,b,l,c,a].find(x=>x.error)?.error;if(first)setError(first.message);else{setProfiles((p.data||[]) as Profile[]);setBoilers((b.data||[]) as Boiler[]);setLimits((l.data||[]) as Limit[]);setItems((c.data||[]) as Checklist[]);setAudits((a.data||[]) as Audit[]);setError("")}setLoading(false)},[]);
 useEffect(()=>{void load();const channel=supabase.channel("admin-panel-live").on("postgres_changes",{event:"*",schema:"public",table:"profiles"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"boilers"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"operational_limits"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"safety_checklist_items"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[load]);
 const fail=(message:string)=>setError(message),ok=(message:string)=>{setError("");notify(message);void load()};
 const updateUser=async(id:string,values:Partial<Profile>)=>{const{error:e}=await supabase.from("profiles").update(values).eq("id",id);e?fail(e.message):ok("User access updated")};
 const addBoiler=async(e:FormEvent)=>{e.preventDefault();const{error:e2}=await supabase.from("boilers").insert({...boilerForm,code:boilerForm.code.trim().toUpperCase(),name:boilerForm.name.trim(),capacity_tons:Number(boilerForm.capacity_tons)});if(e2)fail(e2.message);else{setBoilerForm({code:"",name:"",boiler_type:"Fire-tube",capacity_tons:"1"});ok("Boiler added")}};
 const updateBoiler=async(row:Boiler,values:Partial<Boiler>)=>{const{error:e}=await supabase.from("boilers").update(values).eq("id",row.id);e?fail(e.message):ok("Boiler updated")};
 const removeBoiler=async(row:Boiler)=>{if(!confirm(`Delete ${row.code}? Existing linked records may prevent deletion.`))return;const{error:e}=await supabase.from("boilers").delete().eq("id",row.id);e?fail(e.message):ok("Boiler removed")};
 const updateLimit=async(row:Limit,values:Partial<Limit>)=>{const next={...row,...values};if(Number(next.minimum)>=Number(next.maximum)){fail("Minimum must be less than maximum");return}const{error:e}=await supabase.from("operational_limits").update({minimum:Number(next.minimum),maximum:Number(next.maximum)}).eq("id",row.id);e?fail(e.message):ok("Operational limit updated")};
 const addItem=async(e:FormEvent)=>{e.preventDefault();if(!itemText.trim())return;const{error:e2}=await supabase.from("safety_checklist_items").insert({item_text:itemText.trim(),sort_order:items.length+1});if(e2)fail(e2.message);else{setItemText("");ok("Checklist item added")}};
 const removeItem=async(row:Checklist)=>{if(!confirm(`Delete: ${row.item_text}?`))return;const{error:e}=await supabase.from("safety_checklist_items").delete().eq("id",row.id);e?fail(e.message):ok("Checklist item removed")};
 const tabs:[Tab,string,typeof Users][]=[["users","Users & Roles",Users],["boilers","Boilers",Settings],["limits","Operational Limits",Gauge],["checklist","Checklist",CheckCircle2],["audit","Audit Trail",Activity]];
 return <section className="module-wrap"><div className="page-heading"><div><p className="eyebrow">PROTECTED SYSTEM CONFIGURATION</p><h2>Admin panel</h2><span>Changes are stored in Supabase and enforced through administrator-only policies.</span></div><button className="secondary" onClick={()=>void load()}><RefreshCw/>Refresh</button></div>{error&&<div className="monitor-error">{error}</div>}<div className="admin-tabs">{tabs.map(([id,label,Icon])=><button className={tab===id?"active":""} key={id} onClick={()=>setTab(id)}><Icon/>{label}</button>)}</div>{loading?<div className="panel monitor-loading"><LoaderCircle className="spin"/>Loading administration data…</div>:<>
 {tab==="users"&&<div className="admin-list">{profiles.map(user=>{const mainAdmin=user.email.toLowerCase()==="muthuramanajith28@gmail.com";return <article className="panel admin-user" key={user.id}><div><b>{user.full_name||"Unnamed user"}{mainAdmin?" · Main admin":""}</b><span>{user.email}</span><small>Joined {new Date(user.created_at).toLocaleDateString()}</small></div><select disabled={mainAdmin} value={user.role} onChange={e=>void updateUser(user.id,{role:e.target.value as Profile["role"]})}><option value="admin">Admin</option><option value="supervisor">Supervisor</option><option value="operator">Operator</option><option value="technician">Technician</option></select><select disabled={mainAdmin} value={user.approval_status} onChange={e=>void updateUser(user.id,{approval_status:e.target.value as Profile["approval_status"],is_active:e.target.value==="approved"})}><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><button disabled={mainAdmin} className={user.is_active?"admin-active":"admin-inactive"} onClick={()=>void updateUser(user.id,{is_active:!user.is_active})}>{user.is_active?"Active":"Blocked"}</button></article>})}</div>}
 {tab==="boilers"&&<><form className="panel admin-create-grid" onSubmit={addBoiler}><input placeholder="Boiler ID (SG-04)" required value={boilerForm.code} onChange={e=>setBoilerForm({...boilerForm,code:e.target.value})}/><input placeholder="Boiler name" required value={boilerForm.name} onChange={e=>setBoilerForm({...boilerForm,name:e.target.value})}/><input placeholder="Type" required value={boilerForm.boiler_type} onChange={e=>setBoilerForm({...boilerForm,boiler_type:e.target.value})}/><input type="number" min="0.1" step="0.1" required value={boilerForm.capacity_tons} onChange={e=>setBoilerForm({...boilerForm,capacity_tons:e.target.value})}/><button className="primary"><Plus/>Add boiler</button></form><div className="admin-list">{boilers.map(row=><article className="panel admin-boiler" key={row.id}><input value={row.code} onChange={e=>setBoilers(boilers.map(b=>b.id===row.id?{...b,code:e.target.value}:b))}/><input value={row.name} onChange={e=>setBoilers(boilers.map(b=>b.id===row.id?{...b,name:e.target.value}:b))}/><input value={row.boiler_type} onChange={e=>setBoilers(boilers.map(b=>b.id===row.id?{...b,boiler_type:e.target.value}:b))}/><input type="number" min="0.1" step="0.1" value={row.capacity_tons} onChange={e=>setBoilers(boilers.map(b=>b.id===row.id?{...b,capacity_tons:Number(e.target.value)}:b))}/><button className="secondary" onClick={()=>void updateBoiler(row,{code:row.code.trim().toUpperCase(),name:row.name.trim(),boiler_type:row.boiler_type.trim(),capacity_tons:Number(row.capacity_tons)})}>Save</button><button className="danger-icon" onClick={()=>void removeBoiler(row)}><Trash2/></button></article>)}</div></>}
 {tab==="limits"&&<div className="admin-list">{limits.map(row=><article className="panel admin-limit" key={row.id}><div><b>{row.label}</b><span>{row.reading_key} · {row.unit}</span></div><label>Minimum<input type="number" step="0.1" value={row.minimum} onChange={e=>setLimits(limits.map(l=>l.id===row.id?{...l,minimum:Number(e.target.value)}:l))}/></label><label>Maximum<input type="number" step="0.1" value={row.maximum} onChange={e=>setLimits(limits.map(l=>l.id===row.id?{...l,maximum:Number(e.target.value)}:l))}/></label><button className="primary" onClick={()=>void updateLimit(row,{minimum:row.minimum,maximum:row.maximum})}>Save limits</button></article>)}</div>}
 {tab==="checklist"&&<><form className="panel admin-checklist-add" onSubmit={addItem}><input value={itemText} onChange={e=>setItemText(e.target.value)} placeholder="New safety checklist item" required/><button className="primary"><Plus/>Add item</button></form><div className="admin-list">{items.map((row,index)=><article className="panel admin-check-item" key={row.id}><b>{String(index+1).padStart(2,"0")}</b><input value={row.item_text} onChange={e=>setItems(items.map(i=>i.id===row.id?{...i,item_text:e.target.value}:i))}/><button className="secondary" onClick={async()=>{const{error:e}=await supabase.from("safety_checklist_items").update({item_text:row.item_text.trim()}).eq("id",row.id);e?fail(e.message):ok("Checklist item updated")}}>Save</button><button className="danger-icon" onClick={()=>void removeItem(row)}><Trash2/></button></article>)}</div></>}
 {tab==="audit"&&<div className="admin-list">{audits.length?audits.map(row=><article className="panel audit-row" key={row.id}><ShieldCheck/><div><b>{row.action}</b><span>{row.entity_type||"system"}{row.entity_id?` · ${row.entity_id}`:""}</span></div><time>{new Date(row.created_at).toLocaleString()}</time></article>):<div className="panel empty-panel"><Activity/><h3>No audit activity yet</h3><p>New administrator changes will appear here.</p></div>}</div>}
 </>}</section>;
}
