import { FormEvent, useCallback, useEffect, useState } from "react";
import { Download, FileText, Heart, Megaphone, Trash2, Upload } from "lucide-react";
import type { Session } from "@supabase/supabase-js";
import type { UserProfile } from "./AuthGate";
import { supabase } from "../lib/supabase";
type Announcement={id:number;title:string;message:string;file_name:string|null;file_path:string|null;created_by: string;created_at:string;profiles:{full_name:string}|null;announcement_likes:{user_id:string}[];url?:string};
export function Announcements({session,profile,notify}:{session:Session;profile:UserProfile|null;notify:(s:string)=>void}){
 const[rows,setRows]=useState<Announcement[]>([]),[title,setTitle]=useState(""),[message,setMessage]=useState(""),[file,setFile]=useState<File|null>(null),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{const{data,error:e}=await supabase.from("announcements").select("id,title,message,file_name,file_path,created_by,created_at,profiles(full_name),announcement_likes(user_id)").order("created_at",{ascending:false});if(e){setError(e.message);return}const enriched=await Promise.all(((data||[]) as unknown as Announcement[]).map(async r=>{if(!r.file_path)return r;const{data:s}=await supabase.storage.from("announcements").createSignedUrl(r.file_path,3600);return{...r,url:s?.signedUrl}}));setRows(enriched);setError("")},[]);
 useEffect(()=>{void load();const c=supabase.channel("announcements-live").on("postgres_changes",{event:"*",schema:"public",table:"announcements"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"announcement_likes"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(c)}},[load]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);let path:string|null=null;if(file){if(file.size>20*1024*1024){setError("Attachment must be 20 MB or smaller");setSaving(false);return}path=`${session.user.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const{error:u}=await supabase.storage.from("announcements").upload(path,file);if(u){setError(u.message);setSaving(false);return}}const{error:i}=await supabase.from("announcements").insert({title,message,file_name:file?.name||null,file_path:path,created_by:session.user.id});if(i)setError(i.message);else{setTitle("");setMessage("");setFile(null);notify("Announcement published")}setSaving(false)};
 const like=async(r:Announcement)=>{const liked=r.announcement_likes.some(l=>l.user_id===session.user.id);const q=supabase.from("announcement_likes");const{error:e}=liked?await q.delete().eq("announcement_id",r.id).eq("user_id",session.user.id):await q.insert({announcement_id:r.id,user_id:session.user.id});if(e)setError(e.message)};
 const remove=async(r:Announcement)=>{if(!confirm("Delete this announcement?"))return;if(r.file_path)await supabase.storage.from("announcements").remove([r.file_path]);const{error:e}=await supabase.from("announcements").delete().eq("id",r.id);if(e)setError(e.message);else notify("Announcement deleted")};
 return <section className="module-wrap"><div className="page-heading"><div><p className="eyebrow">PLANT COMMUNICATION</p><h2>Announcements</h2><span>Every signed-in user can view and download published files.</span></div></div>{error&&<div className="monitor-error">{error}</div>}<form className="announcement-form panel" onSubmit={submit}><Megaphone/><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Announcement title" required/><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Message or instructions"/><label className="photo-upload"><Upload/><div><b>{file?.name||"Attach PDF, image or document"}</b><span>Maximum 20 MB</span></div><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary" disabled={saving}>{saving?"Publishing…":"Publish"}</button></form><div className="announcement-list">{rows.map(r=>{const liked=r.announcement_likes.some(l=>l.user_id===session.user.id);const canDelete=profile?.role==="admin"||r.created_by===session.user.id;return <article className="panel announcement-card" key={r.id}><div className="announcement-icon"><Megaphone/></div><div><span>{r.profiles?.full_name||"SteamGuard user"} · {new Date(r.created_at).toLocaleString()}</span><h3>{r.title}</h3><p>{r.message||"No additional message"}</p>{r.url&&<a href={r.url} download={r.file_name||undefined} target="_blank" rel="noreferrer"><FileText/>{r.file_name}<Download/></a>}<div className="announcement-actions"><button className={liked?"liked":""} onClick={()=>void like(r)}><Heart/> {r.announcement_likes.length}</button>{canDelete&&<button onClick={()=>void remove(r)}><Trash2/>Delete</button>}</div></div></article>})}</div></section>;
}
