import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Download, LogIn, LogOut, Users } from "lucide-react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "../lib/supabase";

type Worker={id:string;full_name:string;email:string;assigned_boiler_id:number|null};
type Boiler={id:number;code:string;name:string};
type AttendanceRow={id:number;status:"in"|"out";event_at:string;workers:{full_name:string;email:string}|null;boilers:{code:string;name:string}|null};
const html=(value:string)=>value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]||char));

export function Attendance({session,notify}:{session:Session;notify:(text:string)=>void}){
 const[workers,setWorkers]=useState<Worker[]>([]),[boilers,setBoilers]=useState<Boiler[]>([]),[rows,setRows]=useState<AttendanceRow[]>([]),[workerId,setWorkerId]=useState(""),[boilerId,setBoilerId]=useState(""),[status,setStatus]=useState<"in"|"out">("in"),[from,setFrom]=useState(""),[to,setTo]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{const[w,b,a]=await Promise.all([supabase.from("workers").select("id,full_name,email,assigned_boiler_id").eq("is_active",true).order("full_name"),supabase.from("boilers").select("id,code,name").order("code"),supabase.from("attendance_records").select("id,status,event_at,workers(full_name,email),boilers(code,name)").order("event_at",{ascending:false})]);if(w.error||b.error||a.error)setError(w.error?.message||b.error?.message||a.error?.message||"Attendance data unavailable");else{setWorkers((w.data||[]) as Worker[]);setBoilers((b.data||[]) as Boiler[]);setRows((a.data||[]) as unknown as AttendanceRow[]);setError("")}},[]);
 useEffect(()=>{void load();const channel=supabase.channel("attendance-history").on("postgres_changes",{event:"*",schema:"public",table:"attendance_records"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[load]);
 const mark=async(e:FormEvent)=>{e.preventDefault();setSaving(true);const{error:saveError}=await supabase.rpc("record_worker_attendance",{target_worker_id:workerId,target_boiler_id:Number(boilerId),next_status:status});if(saveError)setError(saveError.message);else{notify(`Attendance ${status.toUpperCase()} recorded`);setError("")}setSaving(false)};
 const today=new Date().toISOString().slice(0,10);const todayRows=useMemo(()=>rows.filter(row=>row.event_at.slice(0,10)===today),[rows,today]);
 const exportPdf=(range:boolean)=>{if(range&&(!from||!to)){setError("Select both From and To dates");return}const chosen=range?rows.filter(row=>row.event_at.slice(0,10)>=from&&row.event_at.slice(0,10)<=to):rows;const body=chosen.map(row=>`<tr><td>${html(new Date(row.event_at).toLocaleDateString())}</td><td>${html(new Date(row.event_at).toLocaleTimeString())}</td><td>${html(row.workers?.full_name||"Worker")}</td><td>${html(row.boilers?.code||"Boiler")}</td><td>${row.status.toUpperCase()}</td></tr>`).join("");const win=window.open("","_blank");if(!win)return;win.document.write(`<title>SteamGuard Attendance Report</title><style>body{font-family:Arial;padding:30px;color:#10233b}h1{margin-bottom:4px}p{color:#64748b}table{width:100%;border-collapse:collapse;margin-top:22px}th,td{border:1px solid #cbd5e1;padding:9px;text-align:left}th{background:#eaf3ff}</style><h1>SteamGuard Attendance Report</h1><p>${range?`${html(from)} to ${html(to)}`:"Full attendance data"} · ${chosen.length} record(s)</p><table><thead><tr><th>Date</th><th>Time</th><th>Worker</th><th>Boiler</th><th>Status</th></tr></thead><tbody>${body}</tbody></table><script>window.onload=()=>window.print()<\/script>`);win.document.close()};
 return <section className="module-wrap"><div className="page-heading"><div><p className="eyebrow">WORKFORCE ATTENDANCE</p><h2>Attendance</h2><span>Select a worker and boiler; IN/OUT date and time are stored automatically.</span></div><div className="attendance-count"><Users/><span>Today</span><b>{todayRows.length} record(s)</b></div></div>{error&&<div className="monitor-error">{error}</div>}<form className="attendance-form panel" onSubmit={mark}><label>Worker<select required value={workerId} onChange={e=>{const id=e.target.value;setWorkerId(id);const worker=workers.find(w=>w.id===id);if(worker?.assigned_boiler_id)setBoilerId(String(worker.assigned_boiler_id))}}><option value="">Select worker</option>{workers.map(worker=><option key={worker.id} value={worker.id}>{worker.full_name}</option>)}</select></label><label>Boiler<select required value={boilerId} onChange={e=>setBoilerId(e.target.value)}><option value="">Select boiler</option>{boilers.map(boiler=><option key={boiler.id} value={boiler.id}>{boiler.code} · {boiler.name}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value as "in"|"out")}><option value="in">IN</option><option value="out">OUT</option></select></label><button className={`primary attendance-submit ${status}`} disabled={saving}>{status==="in"?<LogIn/>:<LogOut/>}{saving?"Saving…":`Mark ${status.toUpperCase()}`}</button></form><div className="export-panel panel"><div><b>Attendance PDF export</b><span>Full history or selected date range.</span></div><button className="secondary" onClick={()=>exportPdf(false)}><Download/>Full data export</button><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/><button className="primary" onClick={()=>exportPdf(true)}><Download/>Date-wise export</button></div><div className="attendance-list">{rows.map(row=><article className="panel attendance-row" key={row.id}><div className={`attendance-event-icon ${row.status}`}>{row.status==="in"?<LogIn/>:<LogOut/>}</div><div><b>{row.workers?.full_name||"Worker"}</b><span>{row.workers?.email||""}</span></div><div><b>{row.boilers?.code||"Boiler"}</b><span>{row.boilers?.name||""}</span></div><strong className={`worker-state ${row.status}`}>{row.status.toUpperCase()}</strong><time>{new Date(row.event_at).toLocaleString()}</time></article>)}</div>{!rows.length&&<div className="empty-panel panel"><CheckCircle2/><h3>No attendance records</h3><p>The first IN/OUT entry will appear here.</p></div>}</section>;
}
