import { FormEvent, ReactNode, useCallback, useEffect, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { AlertCircle, CheckCircle2, Clock3, Flame, LoaderCircle, LockKeyhole, Mail, RefreshCw, ShieldCheck, UserRound, XCircle } from "lucide-react";
import { supabase } from "../lib/supabase";

export type UserProfile = {id:string;full_name:string;role:"admin"|"supervisor"|"operator"|"technician";is_active:boolean;approval_status:"pending"|"approved"|"rejected"};
const timeout=<T,>(promise:PromiseLike<T>,ms=6000)=>Promise.race([Promise.resolve(promise),new Promise<T>((_,reject)=>window.setTimeout(()=>reject(new Error("Connection timed out")),ms))]);

export function AuthGate({children}:{children:(session:Session,profile:UserProfile|null)=>ReactNode}){
 const[session,setSession]=useState<Session|null>(null),[profile,setProfile]=useState<UserProfile|null>(null),[loading,setLoading]=useState(true),[accessError,setAccessError]=useState("");
 const loadProfile=useCallback(async(nextSession:Session)=>{setAccessError("");try{const{data,error}=await timeout(supabase.from("profiles").select("id,full_name,role,is_active,approval_status").eq("id",nextSession.user.id).maybeSingle());if(error)throw error;if(!data)throw new Error("Account profile was not found");setProfile(data as UserProfile)}catch(e){setProfile(null);setAccessError(e instanceof Error?e.message:"Unable to verify account")}finally{setLoading(false)}},[]);
 const initialise=useCallback(async()=>{setLoading(true);setAccessError("");try{const{data,error}=await timeout(supabase.auth.getSession(),4000);if(error)throw error;setSession(data.session);if(data.session)await loadProfile(data.session);else setLoading(false)}catch(e){setAccessError(e instanceof Error?e.message:"Unable to open SteamGuard");setLoading(false)}},[loadProfile]);
 useEffect(()=>{void initialise();const{data}=supabase.auth.onAuthStateChange((event,nextSession)=>{if(event==="INITIAL_SESSION")return;setSession(nextSession);if(nextSession)void loadProfile(nextSession);else{setProfile(null);setLoading(false)}});return()=>data.subscription.unsubscribe()},[initialise,loadProfile]);
 if(loading)return <div className="auth-loading"><LoaderCircle className="spin"/><span>Checking account access…</span></div>;
 if(accessError)return <div className="auth-loading auth-retry"><AlertCircle/><span>{accessError}</span><button className="secondary" onClick={()=>void initialise()}><RefreshCw/>Retry</button><button className="secondary" onClick={()=>void supabase.auth.signOut()}>Sign out</button></div>;
 if(!session)return <LoginPage/>;
 if(!profile)return <div className="auth-loading"><AlertCircle/><span>Account profile unavailable</span></div>;
 if(profile.approval_status!=="approved"||!profile.is_active)return <ApprovalStatus profile={profile}/>;
 return <>{children(session,profile)}</>;
}

function LoginPage(){
 const[mode,setMode]=useState<"login"|"signup">("login"),[fullName,setFullName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState(""),[submitting,setSubmitting]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const submit=async(event:FormEvent)=>{event.preventDefault();setSubmitting(true);setError("");setSuccess("");if(mode==="signup"){if(password!==confirmPassword){setError("Passwords do not match");setSubmitting(false);return}const{data,error:signUpError}=await supabase.auth.signUp({email,password,options:{data:{full_name:fullName}}});if(signUpError)setError(signUpError.message);else{setSuccess(data.session?"Account created. Waiting for administrator approval.":"Account created. Sign in after administrator approval.");setFullName("");setEmail("");setPassword("");setConfirmPassword("")}}else{const{error:signInError}=await supabase.auth.signInWithPassword({email,password});if(signInError)setError(signInError.message)}setSubmitting(false)};
 return <main className="login-page"><section className="login-brand"><div className="login-logo"><ShieldCheck/><Flame/></div><p>STEAMGUARD OPERATIONS PLATFORM</p><h1>Safer records.<br/>Clearer decisions.</h1><span>Secure operational records, shift continuity, maintenance tracking and safety oversight for qualified boiler personnel.</span><div className="login-security"><LockKeyhole/><div><b>Protected operational access</b><small>Every sign-in and important activity can be audited.</small></div></div></section><section className="login-panel"><form className="login-card" onSubmit={submit}><div className="login-mobile-logo"><ShieldCheck/><b>SteamGuard</b></div><div className="auth-tabs"><button type="button" className={mode==="login"?"active":""} onClick={()=>{setMode("login");setError("");setSuccess("")}}>Sign in</button><button type="button" className={mode==="signup"?"active":""} onClick={()=>{setMode("signup");setError("");setSuccess("")}}>Create account</button></div><p className="eyebrow">{mode==="login"?"AUTHORIZED PERSONNEL ONLY":"NEW OPERATOR REGISTRATION"}</p><h2>{mode==="login"?"Welcome back":"Create account"}</h2><span>{mode==="login"?"Sign in using your approved account.":"Register first; the administrator will approve your access."}</span>{error&&<div className="auth-error"><AlertCircle/>{error}</div>}{success&&<div className="auth-success"><CheckCircle2/>{success}</div>}{mode==="signup"&&<label><span>Full name</span><div><UserRound/><input value={fullName} onChange={e=>setFullName(e.target.value)} required/></div></label>}<label><span>Email address</span><div><Mail/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div></label><label><span>Password</span><div><LockKeyhole/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} required/></div></label>{mode==="signup"&&<label><span>Confirm password</span><div><LockKeyhole/><input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} minLength={6} required/></div></label>}<button className="primary login-button" disabled={submitting}>{submitting?<><LoaderCircle className="spin"/>Please wait…</>:mode==="login"?"Sign in securely":"Create account"}</button><p className="login-help">{mode==="login"?"Only administrator-approved users can enter SteamGuard.":"Your account remains pending until administrator approval."}</p></form><p className="login-disclaimer">SteamGuard is an operational record-management and decision-support system. It does not replace certified boiler controls, alarms, safety interlocks, PLC systems, safety valves, emergency shutdown systems, manufacturer instructions, approved operating procedures, or decisions made by qualified personnel.</p></section></main>;
}

function ApprovalStatus({profile}:{profile:UserProfile}){const rejected=profile.approval_status==="rejected";return <main className="approval-page"><section className="approval-card panel"><div className={`approval-icon ${rejected?"rejected":""}`}>{rejected?<XCircle/>:<Clock3/>}</div><p className="eyebrow">STEAMGUARD ACCESS CONTROL</p><h1>{rejected?"Access request rejected":"Approval pending"}</h1><p>{rejected?"Your registration was not approved. Contact the SteamGuard administrator.":"Your account has been created. The administrator must approve access before you can continue."}</p><div><b>{profile.full_name}</b><span>{profile.role}</span></div><button className="secondary" onClick={()=>void supabase.auth.signOut()}>Sign out</button></section></main>}
