import { FormEvent, useCallback, useEffect, useState } from "react";
import { Camera, Database, ExternalLink, Image, Upload } from "lucide-react";
import type { Session } from "@supabase/supabase-js";
import type { UserProfile } from "./AuthGate";
import { supabase } from "../lib/supabase";

type EventRecord={id:number;boiler_name:string;operator_name:string;event_type:string;notes:string;photo_path:string|null;created_at:string;photo_url?:string};

export function DataStore({session,profile,notify}:{session:Session;profile:UserProfile|null;notify:(text:string)=>void}){
 const[records,setRecords]=useState<EventRecord[]>([]),[file,setFile]=useState<File|null>(null),[form,setForm]=useState({boiler_name:"",event_type:"Boiler On",notes:""}),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{const{data,error:loadError}=await supabase.from("boiler_event_records").select("*").order("created_at",{ascending:false});if(loadError){setError(loadError.message);return}const enriched=await Promise.all(((data||[]) as EventRecord[]).map(async record=>{if(!record.photo_path)return record;const{data:signed}=await supabase.storage.from("boiler-references").createSignedUrl(record.photo_path,3600);return{...record,photo_url:signed?.signedUrl}}));setRecords(enriched);setError("")},[]);
 useEffect(()=>{void load();const c=supabase.channel("boiler-data-store").on("postgres_changes",{event:"INSERT",schema:"public",table:"boiler_event_records"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(c)}},[load]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError("");let photoPath:string|null=null;if(file){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");photoPath=`${session.user.id}/${Date.now()}-${safe}`;const{error:uploadError}=await supabase.storage.from("boiler-references").upload(photoPath,file);if(uploadError){setError(uploadError.message);setSaving(false);return}}
 const operatorName=profile?.full_name||session.user.email?.split("@")[0]||"Operator";const{error:saveError}=await supabase.from("boiler_event_records").insert({boiler_name:form.boiler_name,operator_name:operatorName,event_type:form.event_type,notes:form.notes,photo_path:photoPath,created_by:session.user.id});if(saveError)setError(saveError.message);else{setForm({boiler_name:"",event_type:"Boiler On",notes:""});setFile(null);notify("Boiler event stored with reference");void load()}setSaving(false)};
 return <section className="module-wrap"><div className="page-heading"><div><p className="eyebrow">HISTORICAL OPERATIONS EVIDENCE</p><h2>Data Store</h2><span>Store boiler ON/OFF and operational events with reference photos for future monitoring.</span></div></div>{error&&<div className="monitor-error">{error}</div>}<form className="data-store-form panel" onSubmit={submit}><div className="data-form-title"><Camera/><div><h3>New boiler event</h3><p>Add an original reading/event with optional photographic evidence.</p></div></div><label>Boiler / Equipment name<input required value={form.boiler_name} onChange={e=>setForm({...form,boiler_name:e.target.value})} placeholder="Example: SG-01 or Main Boiler 1"/></label><label>Event type<select value={form.event_type} onChange={e=>setForm({...form,event_type:e.target.value})}><option>Boiler On</option><option>Boiler Off</option><option>Inspection</option><option>Maintenance</option><option>Other</option></select></label><label className="data-notes">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Record the state, readings, observation or action taken…"/></label><label className="photo-upload"><Upload/><div><b>{file?file.name:"Upload reference photo"}</b><span>JPG, PNG or WebP</span></div><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary" disabled={saving}>{saving?"Storing…":"Store event"}</button></form><div className="data-records">{records.map(record=><article className="panel data-record" key={record.id}>{record.photo_url?<a href={record.photo_url} target="_blank" rel="noreferrer"><img src={record.photo_url} alt={`${record.boiler_name} ${record.event_type}`}/><ExternalLink/></a>:<div className="no-photo"><Image/></div>}<div><span>{record.event_type}</span><h3>{record.boiler_name}</h3><p>{record.notes||"No notes added"}</p><small>{record.operator_name} · {new Date(record.created_at).toLocaleString()}</small></div></article>)}</div>{!records.length&&<div className="empty-panel panel"><Database/><h3>No stored events</h3><p>Boiler ON/OFF events and reference photos will appear here.</p></div>}</section>;
}
