import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Download, Fuel, Plus, Trash2 } from "lucide-react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "../lib/supabase";
type FuelRow={id:number;usage_date:string;boiler_name:string;quantity:number;unit:string;notes:string;created_by:string;created_at:string};
const safe=(v:string)=>v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));
export function FuelUsage({session,notify}:{session:Session;notify:(s:string)=>void}){
 const[rows,setRows]=useState<FuelRow[]>([]),[form,setForm]=useState({usage_date:new Date().toISOString().slice(0,10),boiler_name:"",quantity:"",unit:"kg",notes:""}),[from,setFrom]=useState(""),[to,setTo]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{const{data,error:e}=await supabase.from("fuel_usage").select("*").order("usage_date",{ascending:false});if(e)setError(e.message);else{setRows((data||[]) as FuelRow[]);setError("")}},[]);
 useEffect(()=>{void load();const c=supabase.channel("fuel-usage").on("postgres_changes",{event:"*",schema:"public",table:"fuel_usage"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(c)}},[load]);
 const total=useMemo(()=>rows.reduce((sum,r)=>sum+Number(r.quantity),0),[rows]);
 const submit=async(e:FormEvent)=>{e.preventDefault();const{error:e2}=await supabase.from("fuel_usage").insert({...form,quantity:Number(form.quantity),created_by:session.user.id});if(e2)setError(e2.message);else{setForm({...form,quantity:"",notes:""});notify("Daily fuel usage saved")}};
 const remove=async(row:FuelRow)=>{if(!confirm("Delete this fuel record?"))return;const{error:e}=await supabase.from("fuel_usage").delete().eq("id",row.id);if(e)setError(e.message);else notify("Fuel record deleted")};
 const exportPdf=(range:boolean)=>{if(range&&(!from||!to)){setError("Select both From and To dates");return}const selected=range?rows.filter(r=>r.usage_date>=from&&r.usage_date<=to):rows;const sum=selected.reduce((a,r)=>a+Number(r.quantity),0);const body=selected.map(r=>`<tr><td>${safe(r.usage_date)}</td><td>${safe(r.boiler_name)}</td><td>${r.quantity} ${safe(r.unit)}</td><td>${safe(r.notes||"—")}</td></tr>`).join("");const w=window.open("","_blank");if(!w)return;w.document.write(`<title>SteamGuard Fuel Report</title><style>body{font-family:Arial;padding:32px;color:#10233b}h1{margin-bottom:4px}p{color:#5c6b7a}table{border-collapse:collapse;width:100%;margin-top:24px}th,td{border:1px solid #ccd5df;padding:9px;text-align:left}th{background:#edf4fb}.total{font-size:18px;font-weight:bold;margin-top:18px}</style><h1>SteamGuard Fuel Usage Report</h1><p>${range?`${safe(from)} to ${safe(to)}`:"Full data export"}</p><table><thead><tr><th>Date</th><th>Boiler</th><th>Usage</th><th>Notes</th></tr></thead><tbody>${body}</tbody></table><div class="total">Total usage: ${sum.toFixed(2)} ${safe(selected[0]?.unit||"kg")}</div><script>window.onload=()=>window.print()<\/script>`);w.document.close()};
 return <section className="module-wrap"><div className="page-heading"><div><p className="eyebrow">DAILY CONSUMPTION</p><h2>Fuel calculation</h2><span>Daily entries accumulate into a permanent total.</span></div><div className="fuel-total"><Fuel/><span>Total usage</span><b>{total.toFixed(2)} {rows[0]?.unit||"kg"}</b></div></div>{error&&<div className="monitor-error">{error}</div>}<form className="fuel-form panel" onSubmit={submit}><label>Date<input type="date" value={form.usage_date} onChange={e=>setForm({...form,usage_date:e.target.value})} required/></label><label>Boiler<input value={form.boiler_name} onChange={e=>setForm({...form,boiler_name:e.target.value})} placeholder="SG-01" required/></label><label>Fuel used<input type="number" min="0" step="0.01" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})} required/></label><label>Unit<select value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}><option>kg</option><option>litre</option><option>ton</option></select></label><label className="fuel-notes">Notes<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary"><Plus/>Add usage</button></form><div className="export-panel panel"><div><b>PDF Export</b><span>Use the browser print dialog and select “Save as PDF”.</span></div><button className="secondary" onClick={()=>exportPdf(false)}><Download/>Full data export</button><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/><button className="primary" onClick={()=>exportPdf(true)}><Download/>Selected dates</button></div><div className="fuel-list">{rows.map(r=><article className="panel fuel-row" key={r.id}><time>{new Date(`${r.usage_date}T00:00:00`).toLocaleDateString()}</time><div><b>{r.boiler_name}</b><span>{r.notes||"No notes"}</span></div><strong>{Number(r.quantity).toFixed(2)} {r.unit}</strong><button onClick={()=>void remove(r)}><Trash2/></button></article>)}</div></section>;
}
