import { FormEvent, useCallback, useEffect, useState } from "react";
import { AlertTriangle, BookOpen, CheckCircle2, Flame, Gauge, LoaderCircle, Thermometer, Waves } from "lucide-react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "../lib/supabase";

type Boiler={id:number;code:string;name:string;boiler_type:string};
type Reading={id:number;boiler_id:number;pressure:number;water_level:number;steam_temperature:number;flue_temperature:number;feed_water_temperature:number;furnace_temperature:number;remarks:string;created_at:string;boilers:{code:string;name:string}|null};
type FormState={boiler_id:string;pressure:number;water_level:number;steam_temperature:number;flue_temperature:number;feed_water_temperature:number;furnace_temperature:number;remarks:string};
const initial:FormState={boiler_id:"",pressure:0,water_level:0,steam_temperature:0,flue_temperature:0,feed_water_temperature:0,furnace_temperature:0,remarks:""};
const limits={pressure:{min:6,max:12},water_level:{min:40,max:80},steam_temperature:{min:150,max:200},flue_temperature:{min:110,max:220}};
const abnormal=(r:Reading)=>r.pressure<limits.pressure.min||r.pressure>limits.pressure.max||r.water_level<limits.water_level.min||r.water_level>limits.water_level.max||r.steam_temperature<limits.steam_temperature.min||r.steam_temperature>limits.steam_temperature.max||r.flue_temperature<limits.flue_temperature.min||r.flue_temperature>limits.flue_temperature.max;

export function LogbookModule({session,notify}:{session:Session;notify:(text:string)=>void}){
 const[boilers,setBoilers]=useState<Boiler[]>([]),[form,setForm]=useState<FormState>(initial),[saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{void supabase.from("boilers").select("id,code,name,boiler_type").order("code").then(({data,error:e})=>{if(e)setError(e.message);else setBoilers((data||[]) as Boiler[])})},[]);
 const numberField=(key:keyof FormState,value:string)=>setForm({...form,[key]:Number(value)});
 const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError("");const payload={...form,boiler_id:Number(form.boiler_id),created_by:session.user.id};const{error:saveError}=await supabase.from("logbook_entries").insert(payload);if(saveError)setError(saveError.message);else{setForm(initial);notify("Logbook reading saved and dashboard updated")}setSaving(false)};
 const fields:[keyof FormState,string,string][]=[["pressure","Steam pressure","bar"],["water_level","Water level","%"],["steam_temperature","Steam temperature","°C"],["flue_temperature","Flue gas temperature","°C"],["feed_water_temperature","Feed-water temperature","°C"],["furnace_temperature","Furnace temperature","°C"]];
 return <section className="module-wrap"><div className="page-heading"><div><p className="eyebrow">DIGITAL OPERATIONS RECORD</p><h2>New logbook entry</h2><span>Only submitted operator readings are displayed on the dashboard.</span></div></div>{error&&<div className="monitor-error">{error}</div>}<form className="entry-form panel" onSubmit={submit}><div className="form-intro"><div><h3>Boiler readings</h3><p>Select one of the three registered main boilers.</p></div><BookOpen/></div><div className="form-grid"><label><span>Boiler</span><select required value={form.boiler_id} onChange={e=>setForm({...form,boiler_id:e.target.value})}><option value="">Select boiler</option>{boilers.map(b=><option key={b.id} value={b.id}>{b.code} · {b.name}</option>)}</select></label>{fields.map(([key,label,unit])=><label key={key}><span>{label}</span><div className="input-unit"><input type="number" min="0" step="0.1" value={String(form[key])} onChange={e=>numberField(key,e.target.value)}/><b>{unit}</b></div></label>)}</div><label className="notes"><span>Operator remarks</span><textarea value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})} placeholder="Add original observations or pending actions…"/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setForm(initial)}>Clear</button><button className="primary" disabled={saving}><CheckCircle2/>{saving?"Submitting…":"Submit reading"}</button></div></form></section>;
}

export function LatestReadings(){
 const[readings,setReadings]=useState<Reading[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{const{data,error:e}=await supabase.from("logbook_entries").select("id,boiler_id,pressure,water_level,steam_temperature,flue_temperature,feed_water_temperature,furnace_temperature,remarks,created_at,boilers(code,name)").order("created_at",{ascending:false});if(e)setError(e.message);else{const latest=new Map<number,Reading>();for(const row of (data||[]) as unknown as Reading[])if(!latest.has(row.boiler_id))latest.set(row.boiler_id,row);setReadings([...latest.values()]);setError("")}setLoading(false)},[]);
 useEffect(()=>{void load();const c=supabase.channel("dashboard-logbook").on("postgres_changes",{event:"INSERT",schema:"public",table:"logbook_entries"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(c)}},[load]);
 if(loading)return <div className="panel monitor-loading"><LoaderCircle className="spin"/>Loading submitted readings…</div>;
 if(error)return <div className="monitor-error">{error}</div>;
 if(!readings.length)return <div className="panel empty-reading"><BookOpen/><div><h3>No readings recorded</h3><p>Dashboard values will appear only after a user submits a logbook entry.</p></div></div>;
 const warnings=readings.filter(abnormal);
 return <section className="latest-readings">{warnings.length>0&&<div className="alert-banner"><AlertTriangle/><div><b>Reading warning:</b> {warnings.map(r=>r.boilers?.code||"Boiler").join(", ")} contains value(s) outside configured limits.</div></div>}<div className="monitor-heading"><div><p className="eyebrow">LATEST SUBMITTED DATA</p><h3>Original operator readings</h3></div></div><div className="latest-reading-grid">{readings.map(r=><article className={`panel latest-reading-card ${abnormal(r)?"has-warning":""}`} key={r.id}><div className="latest-reading-head"><div><span>{r.boilers?.code||"Boiler"}</span><h4>{r.boilers?.name||"Main boiler"}</h4></div><time>{new Date(r.created_at).toLocaleString()}</time></div><div className="reading-values"><div><Gauge/><span>Pressure</span><b>{r.pressure} bar</b></div><div><Waves/><span>Water level</span><b>{r.water_level}%</b></div><div><Thermometer/><span>Steam temp.</span><b>{r.steam_temperature}°C</b></div><div><Flame/><span>Flue temp.</span><b>{r.flue_temperature}°C</b></div></div>{r.remarks&&<p>{r.remarks}</p>}</article>)}</div></section>;
}
