import { useCallback, useEffect, useState } from "react";
import { CalendarClock, Download, LoaderCircle, Timer } from "lucide-react";
import { supabase } from "../lib/supabase";

type RuntimeSession = { id:number; started_at:string; stopped_at:string|null; duration_seconds:number|null; boilers:{code:string;name:string}|null };
const clock=(seconds:number)=>{const safe=Math.max(0,Math.floor(seconds));return [Math.floor(safe/3600),Math.floor((safe%3600)/60),safe%60].map(v=>String(v).padStart(2,"0")).join(":")};
const html=(value:string)=>value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[char]||char));

export function RuntimeHistory(){
 const[records,setRecords]=useState<RuntimeSession[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[now,setNow]=useState(Date.now()),[from,setFrom]=useState(""),[to,setTo]=useState("");
 const load=useCallback(async()=>{const{data,error:loadError}=await supabase.from("boiler_runtime_sessions").select("id,started_at,stopped_at,duration_seconds,boilers(code,name)").order("started_at",{ascending:false});if(loadError)setError(loadError.message);else{setRecords((data||[]) as unknown as RuntimeSession[]);setError("")}setLoading(false)},[]);
 useEffect(()=>{void load();const channel=supabase.channel("runtime-history").on("postgres_changes",{event:"*",schema:"public",table:"boiler_runtime_sessions"},()=>void load()).subscribe();const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>{window.clearInterval(timer);void supabase.removeChannel(channel)}},[load]);
 const duration=(r:RuntimeSession)=>r.duration_seconds??Math.max(0,(now-new Date(r.started_at).getTime())/1000);
 const exportPdf=(range:boolean)=>{
  if(range&&(!from||!to)){setError("Select both From and To dates");return}
  if(range&&from>to){setError("From date cannot be after To date");return}
  const chosen=range?records.filter(row=>{const date=row.started_at.slice(0,10);return date>=from&&date<=to}):records;
  if(!chosen.length){setError("No boiler runtime records found for export");return}
  setError("");
  const totalSeconds=chosen.reduce((sum,row)=>sum+duration(row),0);
  const body=chosen.map(row=>`<tr><td>${html(new Date(row.started_at).toLocaleDateString())}</td><td>${html(row.boilers?.code||"Boiler")}</td><td>${html(row.boilers?.name||"Registered boiler")}</td><td>${html(new Date(row.started_at).toLocaleTimeString())}</td><td>${row.stopped_at?html(new Date(row.stopped_at).toLocaleTimeString()):"Running now"}</td><td>${clock(duration(row))}</td></tr>`).join("");
  const win=window.open("","_blank");if(!win){setError("Allow pop-ups to export the PDF");return}
  win.document.write(`<title>SteamGuard Boiler Runtime Report</title><style>body{font-family:Arial;padding:30px;color:#10233b}h1{margin-bottom:4px}p{color:#64748b}table{width:100%;border-collapse:collapse;margin-top:22px}th,td{border:1px solid #cbd5e1;padding:9px;text-align:left}th{background:#eaf3ff}.total{font-size:18px;font-weight:bold;margin-top:18px}</style><h1>SteamGuard Boiler Runtime Report</h1><p>${range?`${html(from)} to ${html(to)}`:"Overall runtime export"} · ${chosen.length} record(s)</p><table><thead><tr><th>Date</th><th>Boiler ID</th><th>Boiler</th><th>Start time</th><th>Stop time</th><th>Total runtime</th></tr></thead><tbody>${body}</tbody></table><div class="total">Combined runtime: ${clock(totalSeconds)}</div><script>window.onload=()=>window.print()<\/script>`);win.document.close();
 };
 return <section className="module-wrap"><div className="page-heading"><div><p className="eyebrow">BOILER UTILIZATION RECORD</p><h2>Run history</h2><span>Stored start, stop, and total running time for every boiler.</span></div></div>{error&&<div className="monitor-error">{error}</div>}{!loading&&records.length>0&&<div className="export-panel panel"><div><b>Boiler runtime PDF export</b><span>Export every session or only a selected date range.</span></div><button className="secondary" onClick={()=>exportPdf(false)}><Download/>Overall export</button><input aria-label="Runtime export from date" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input aria-label="Runtime export to date" type="date" value={to} onChange={e=>setTo(e.target.value)}/><button className="primary" onClick={()=>exportPdf(true)}><Download/>Date-wise export</button></div>}{loading?<div className="panel monitor-loading"><LoaderCircle className="spin"/>Loading runtime history…</div>:records.length===0?<div className="panel empty-panel"><Timer/><h3>No runtime records yet</h3><p>Turn a boiler Running to begin its first stored session.</p></div>:<div className="runtime-list">{records.map(r=><article className="panel runtime-record" key={r.id}><div className="runtime-record-icon"><CalendarClock/></div><div><span>{r.boilers?.code||"Boiler"}</span><h3>{r.boilers?.name||"Registered boiler"}</h3><p>{new Date(r.started_at).toLocaleDateString()}</p></div><dl><div><dt>Start time</dt><dd>{new Date(r.started_at).toLocaleTimeString()}</dd></div><div><dt>Stop time</dt><dd>{r.stopped_at?new Date(r.stopped_at).toLocaleTimeString():"Running now"}</dd></div><div><dt>Total runtime</dt><dd>{clock(duration(r))}</dd></div></dl><span className={`operation-state ${r.stopped_at?"off":"running"}`}><i/>{r.stopped_at?"Stopped":"Running"}</span></article>)}</div>}</section>;
}
