import { FormEvent, useCallback, useEffect, useState } from "react";
import type { UserProfile } from "./AuthGate";
import { Check, Plus, Trash2, UserCheck, UserPlus, Users, X } from "lucide-react";
import { supabase } from "../lib/supabase";

type Boiler={id:number;code:string};
type Worker={id:string;full_name:string;email:string;assigned_boiler_id:number|null;job_role:"boiler_operator"|"worker";attendance_status:"in"|"out";attendance_changed_at:string;is_active:boolean};
type PendingUser={id:string;full_name:string;email:string;approval_status:"pending"|"rejected"};

export function WorkersList({profile,notify}:{profile:UserProfile|null;notify:(text:string)=>void}){
 const[workers,setWorkers]=useState<Worker[]>([]),[boilers,setBoilers]=useState<Boiler[]>([]),[pending,setPending]=useState<PendingUser[]>([]),[assignments,setAssignments]=useState<Record<string,string>>({}),[show,setShow]=useState(false),[attendanceBoiler,setAttendanceBoiler]=useState(""),[error,setError]=useState("");
 const[form,setForm]=useState({full_name:"",email:"",assignment:"worker"});
 const load=useCallback(async()=>{const[w,b,p]=await Promise.all([supabase.from("workers").select("*").eq("is_active",true).order("full_name"),supabase.from("boilers").select("id,code").order("code"),profile?.role==="admin"?supabase.from("profiles").select("id,full_name,email,approval_status").eq("approval_status","pending").order("created_at"):Promise.resolve({data:[],error:null})]);if(w.error||b.error||p.error)setError(w.error?.message||b.error?.message||p.error?.message||"Unable to load workers");else{setWorkers((w.data||[]) as Worker[]);setBoilers((b.data||[]) as Boiler[]);setPending((p.data||[]) as PendingUser[]);setError("")}},[profile?.role]);
 useEffect(()=>{void load();const channel=supabase.channel("workers-list").on("postgres_changes",{event:"*",schema:"public",table:"workers"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"profiles"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[load]);
 const assignmentPayload=(value:string)=>value==="worker"?{assigned_boiler_id:null,job_role:"worker" as const}:{assigned_boiler_id:Number(value),job_role:"boiler_operator" as const};
 const add=async(e:FormEvent)=>{e.preventDefault();const user=(await supabase.auth.getUser()).data.user;const{error:saveError}=await supabase.from("workers").insert({full_name:form.full_name.trim(),email:form.email.toLowerCase(),...assignmentPayload(form.assignment),created_by:user?.id});if(saveError)setError(saveError.message);else{setShow(false);setForm({full_name:"",email:"",assignment:"worker"});notify("Worker added successfully")}};
 const remove=async(id:string)=>{const{error:e}=await supabase.from("workers").update({is_active:false}).eq("id",id);e?setError(e.message):notify("Worker removed")};
 const attend=async(state:"in"|"out")=>{if(!attendanceBoiler){setError("Select the attendance boiler first");return}const authEmail=(await supabase.auth.getUser()).data.user?.email?.toLowerCase();const worker=workers.find(w=>w.email.toLowerCase()===authEmail);if(!worker){setError("Your login email is not registered in Workers List");return}const{error:e}=await supabase.rpc("record_worker_attendance",{target_worker_id:worker.id,target_boiler_id:Number(attendanceBoiler),next_status:state});if(e)setError(e.message);else{setError("");notify(`Attendance marked ${state.toUpperCase()} and added to history`)}};
 const approve=async(user:PendingUser)=>{const assignment=assignments[user.id];if(!assignment){setError("Select a boiler job or Worker");return}const admin=(await supabase.auth.getUser()).data.user;const{error:workerError}=await supabase.from("workers").insert({full_name:user.full_name,email:user.email.toLowerCase(),...assignmentPayload(assignment),created_by:admin?.id});if(workerError){setError(workerError.message);return}const{error:profileError}=await supabase.from("profiles").update({approval_status:"approved",is_active:true,role:"operator"}).eq("id",user.id);if(profileError)setError(profileError.message);else{notify("User approved and worker assignment saved");void load()}};
 const reject=async(id:string)=>{const{error:e}=await supabase.from("profiles").update({approval_status:"rejected",is_active:false}).eq("id",id);e?setError(e.message):(notify("User registration rejected"),void load())};
 const options=<><option value="">Select job</option>{boilers.map(b=><option key={b.id} value={b.id}>{b.code} · Boiler operator</option>)}<option value="worker">Worker · Can operate any boiler</option></>;
 return <section className="module-wrap"><div className="page-heading"><div><p className="eyebrow">WORKFORCE & ASSIGNMENT</p><h2>Workers list</h2><span>Administrators can add unlimited boiler operators and general workers.</span></div>{profile?.role==="admin"&&<button className="primary" onClick={()=>setShow(!show)}><Plus/>Add worker</button>}</div>{error&&<div className="monitor-error">{error}</div>}
 {profile?.role==="admin"&&pending.length>0&&<section className="pending-approvals"><div className="section-mini-title"><UserPlus/><div><h3>Pending approvals</h3><p>Assign a main-boiler job or the general Worker role.</p></div><b>{pending.length}</b></div>{pending.map(user=><article className="panel approval-row" key={user.id}><div><b>{user.full_name}</b><span>{user.email}</span></div><select value={assignments[user.id]||""} onChange={e=>setAssignments({...assignments,[user.id]:e.target.value})}>{options}</select><button className="approve-button" onClick={()=>void approve(user)}><Check/>Approve</button><button className="reject-button" onClick={()=>void reject(user.id)}><X/>Reject</button></article>)}</section>}
 <div className="attendance-actions panel"><div><UserCheck/><span><b>My attendance</b><small>IN/OUT is automatically added to Attendance history.</small></span></div><select value={attendanceBoiler} onChange={e=>setAttendanceBoiler(e.target.value)}><option value="">Select boiler</option>{boilers.map(b=><option key={b.id} value={b.id}>{b.code}</option>)}</select><button onClick={()=>void attend("in")}>IN</button><button onClick={()=>void attend("out")}>OUT</button></div>
 {show&&<form className="compact-form panel" onSubmit={add}><label>Worker name<input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>Login email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Job assignment<select required value={form.assignment} onChange={e=>setForm({...form,assignment:e.target.value})}>{options}</select></label><button className="primary">Save worker</button></form>}
 <div className="worker-grid">{workers.map(w=><article className="panel worker-card" key={w.id}><div className="worker-avatar"><Users/></div><div><h3>{w.full_name}</h3><p>{w.email}</p><span>{w.job_role==="worker"?"Worker · Any boiler":boilers.find(b=>b.id===w.assigned_boiler_id)?.code||"Boiler operator"}</span></div><b className={`worker-state ${w.attendance_status}`}>{w.attendance_status.toUpperCase()}</b>{profile?.role==="admin"&&<button className="delete-worker" onClick={()=>void remove(w.id)}><Trash2/></button>}<time>Updated {new Date(w.attendance_changed_at).toLocaleString()}</time></article>)}</div>{!workers.length&&<div className="empty-panel panel"><Users/><h3>No workers assigned</h3><p>Administrator can add boiler operators and general workers.</p></div>}</section>;
}
